name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build ./my-express-app --file ./my-express-app/Dockerfile --tag my-image-name:$(date +%s)

    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master

