name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build ./my-express-app --file ./my-express-app/Dockerfile --tag my-image-name:latest

    - name: Run Docker container
      run: docker run -d --name my-container -p 80:80 my-image-name
    
    - name: Verify Docker container is running
      run: docker ps -a  # Lists all running containers to verify the container is up

    
  test:
    runs-on: ubuntu-latest
    needs: build   # Ensure the build job completes first

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run tests with exclusions
      run: |
        docker exec my-container npx mocha liatrio/github-actions/apprentice-action/tests/endpoint.test.js --grep "should return a minified JSON object." --invert
      

